<?php
$txt = array("IWANNAWEB" => "IWANNAWEB");
$txt["index_title"] = "Experience web freedom | iwannaweb.ro";
$txt["index_keywords"] = "cluj web, website cluj, web design, website optimization, wesite creation, web designer, create site, website advertising";
$txt["index_description"] = "Web design, website creation and optimization Cluj, Bistrita, Alba, Mures, Salaj, Bihor, Arad. Create site, website advertisement - Cluj web designer.";
$txt["webdev_title"] = "Experience web freedom | iwannaweb.ro";
$txt["webdev_keywords"] = "cluj web, website cluj, web design, website optimization, wesite creation, web designer, create site, website advertising";
$txt["webdev_description"] = "Web design, website creation and optimization Cluj, Bistrita, Alba, Mures, Salaj, Bihor, Arad. Create site, website advertisement - Cluj web designer.";
$txt["webdevservices_title"] = "Experience web freedom | iwannaweb.ro";
$txt["webdevservices_keywords"] = "cluj web, website cluj, web design, website optimization, wesite creation, web designer, create site, website advertising";
$txt["webdevservices_description"] = "Web design, website creation and optimization Cluj, Bistrita, Alba, Mures, Salaj, Bihor, Arad. Create site, website advertisement - Cluj web designer.";
$txt["webdevpricing_title"] = "Experience web freedom | iwannaweb.ro";
$txt["webdevpricing_keywords"] = "cluj web, website cluj, web design, website optimization, wesite creation, web designer, create site, website advertising";
$txt["webdevpricing_description"] = "Web design, website creation and optimization Cluj, Bistrita, Alba, Mures, Salaj, Bihor, Arad. Create site, website advertisement - Cluj web designer.";
$txt["webdevsoftware_title"] = "Experience web freedom | iwannaweb.ro";
$txt["webdevsoftware_keywords"] = "cluj web, website cluj, web design, website optimization, wesite creation, web designer, create site, website advertising";
$txt["webdevsoftware_description"] = "Web design, website creation and optimization Cluj, Bistrita, Alba, Mures, Salaj, Bihor, Arad. Create site, website advertisement - Cluj web designer.";
$txt["home"] = "HOME";
$txt["webdev"] = "WEB DEVELOPMENT";
$txt["portfolio"] = "PORTFOLIO";
$txt["crypto"] = "CRYPTOCURRENCY";
$txt["blog"] = "BLOG";
$txt["contact"] = "CONTACT";
$txt["services"] = "SERVICES";
$txt["pricing"] = "PRICING";
$txt["software"] = "SOFTWARE";
$txt["archive"] = "ARCHIVE";
$txt["search"] = "SEARCH";
$txt["lang_menu_alt"] = "ENGLISH";
$txt["webdev_small"] = "Web development";
$txt["news"] = "News";
$txt["free_soft"] = "Free software";
$txt["ask_help"] = "Ask for help";
$txt["crypto_small"] = "Cryptocurrencies";
$txt["info"] = "Info";
$txt["trends"] = "Trends";
$txt["twitter_iwannacrypto"] = "@iwannaCrypto";
$txt["social"] = "Social";
$txt["blog_small"] = "Blog";
$txt["recomm"] = "Recommendations";
$txt["telegram"] = "Telegram";
$txt["contact_us"] = "Contact us";
$txt["slogan"] = "Experience web freedom";

?>